/* ==========================================================
   KEYS99 PROJECT PAGE

   Two ways in:
   - /projects/<slug>/  generated by build/generate.js. The page
     already contains the content and the project row
     (window.__KEYS99_PROJECT__), so it renders with no network
     request; the live fetch below only refreshes it.
   - /projects/property-details.html?slug=<slug>  the fallback
     (never indexed) for a project published since the last build.

   The live fetch never replaces a generated page with an error:
   if it fails, the built content stays. Showing "not found" to a
   crawler on a page that has content would read as a soft 404.

   Section markup comes from js/project-core.js, the same code
   the generator uses.
   ========================================================== */

const P = window.Keys99Project;
const SITE_ROOT = window.__KEYS99_ROOT__ || "../";
const params = new URLSearchParams(window.location.search);
const embeddedRow = window.__KEYS99_PROJECT__ || null;
const requestedSlug = window.__KEYS99_SLUG__ || params.get("slug") || (embeddedRow && embeddedRow.slug) || null;

let project = null;
let galleryImages = [];
let currentImage = 0;

const $ = id => document.getElementById(id);

const normalize = row => P.normalizeProject(row, { supabaseUrl: SUPABASE_URL });


/* ---------------- FAVORITES (localStorage, shared across the site) ---------------- */

function getFavorites(){
  try{
    const favorites = JSON.parse(localStorage.getItem("keys99_favorites") || "[]");
    return Array.isArray(favorites) ? favorites : [];
  }catch(_){
    return [];
  }
}

function setFavoriteButtonState(isActive){
  const btn = $("favoriteBtn");
  btn.classList.toggle("saved", isActive);
  btn.textContent = isActive ? "♥" : "♡";
}

function toggleFavorite(){
  if(!project) return;
  let favorites = getFavorites();
  const isActive = favorites.includes(project.id);
  favorites = isActive ? favorites.filter(id => id !== project.id) : [...favorites, project.id];
  try{ localStorage.setItem("keys99_favorites", JSON.stringify(favorites)); }catch(_){}
  setFavoriteButtonState(!isActive);
  showToast(!isActive ? "Added to favorites" : "Removed from favorites");
}


/* ---------------- BOTTOM NAV ---------------- */

function initBottomNav(){
  const bottomNav = $("bottomNav");
  if(!bottomNav) return;
  bottomNav.addEventListener("click", event => {
    const button = event.target.closest("button");
    if(!button) return;
    const target = button.dataset.target;
    if(target === "home") window.location.href = SITE_ROOT + "index.html";
    else if(target === "search") window.location.href = SITE_ROOT + "projects/search.html";
    else if(target === "reels") window.location.href = SITE_ROOT + "reels.html";
    else if(target === "profile") window.location.href = SITE_ROOT + "profile.html";
  });
}


/* ---------------- LOAD ---------------- */

async function loadProject(){

  if(embeddedRow){
    renderProject(normalize(embeddedRow));
  }

  if(!requestedSlug){
    if(!embeddedRow) showError("No project was requested.");
    return;
  }

  try{
    const { data, error } = await supabaseClient
      .from("residential_projects")
      .select(P.PROJECT_DETAIL_SELECT)
      .eq("slug", requestedSlug)
      .eq("moderation_status", "published")
      .is("deleted_at", null)
      .maybeSingle();

    if(error) throw error;

    if(data){
      renderProject(normalize(data));
    }else if(!embeddedRow){
      showError("This project is not available.");
    }
  }catch(error){
    console.error("Keys99 project error:", error);
    if(!embeddedRow) showError("Unable to load project details. Please try again.");
  }
}


/* ---------------- RENDER ---------------- */

function setText(id, text){
  const el = $(id);
  if(el) el.textContent = text;
}

/* Fill a container and show its section only when there is content. */
function fillSection(sectionId, containerId, html){
  $(containerId).innerHTML = html;
  $(sectionId).classList.toggle("hidden", !html.trim());
}

function setCrumb(id, text){
  $(id).textContent = text;
  $(id).classList.toggle("hidden", !text);
  $(id + "Sep").classList.toggle("hidden", !text);
}

function renderProject(p){
  project = p;

  setText("propertyName", p.name);
  setText("crumbName", p.name);
  setCrumb("crumbCity", p.city);
  setCrumb("crumbLocality", p.locality);
  setText("miniBreadcrumb", p.typeLabel);
  setText("propertyType", p.typeLabel);
  setText("developer", p.developer || "—");
  setText("developerName", p.developer || "—");
  setText("developerDescription", p.developerDescription);
  $("developerSection").classList.toggle("hidden", !p.developer);
  $("developer").closest(".developer-line").classList.toggle("hidden", !p.developer);
  setText("propertyLocation", "⌖ " + ([p.address, p.location].filter(Boolean).join(", ") || "Location not available"));
  setText("mapLocation", p.location || "Project Location");
  setText("statusBadge", p.status || "For Sale");
  $("statusBadge").classList.toggle("hidden", !p.status);
  setText("propertyPrice", p.startingPriceText);
  $("priceNote").classList.toggle("hidden", !p.startingPrice);
  setText("priceDisclaimer", p.priceDisclaimer);
  $("priceDisclaimer").classList.toggle("hidden", !p.priceDisclaimer);
  setText("bhk", p.bhkLabels.length ? p.bhkLabels.join(" / ") : "—");
  setText("carpetArea", p.firstArea || "—");
  setText("possession", p.possession || (p.status === "Ready to Move" ? "Ready" : "—"));
  setText("description", p.overview || "Project description will be available soon.");

  const meta = [];
  if(p.rera) meta.push("RERA: " + p.rera);
  if(p.publishedAt){
    const d = new Date(p.publishedAt);
    if(Number.isFinite(d.getTime())) meta.push("Listed on " + d.toLocaleDateString("en-IN", { day:"numeric", month:"short", year:"numeric" }));
  }
  setText("metaLine", meta.join("  ·  "));
  $("reraBadge").hidden = !p.rera;

  const views = $("viewCount");
  views.hidden = p.views <= 0;
  views.textContent = p.views > 0 ? `👁 ${p.views.toLocaleString("en-IN")} ${p.views === 1 ? "view" : "views"}` : "";

  renderGallery(p);

  $("configurationBody").innerHTML = P.renderConfigurationRows(p);
  $("configurationSection").classList.toggle("hidden", !p.configurations.length);

  fillSection("highlightsSection", "highlights", P.renderHighlights(p));
  fillSection("factsSection", "facts", P.renderFacts(p));
  fillSection("floorPlanSection", "floorPlanGrid", P.renderFloorPlans(p));
  fillSection("amenitiesSection", "amenities", P.renderAmenities(p));
  fillSection("specsSection", "specifications", P.renderSpecificationRows(p));
  fillSection("towersSection", "towers", P.renderTowerRows(p));
  fillSection("prosConsSection", "prosCons", P.renderProsCons(p));
  fillSection("faqSection", "faqs", P.renderFaqs(p));

  $("locationAdvantages").innerHTML = P.renderNearbyRows(p);
  $("locationAdvantages").closest(".table-wrap").classList.toggle("hidden", !p.nearby.length);
  $("locationSection").classList.toggle("hidden", !p.nearby.length && !p.location);

  renderMedia(p);
  setupEmiCalculator(p.startingPrice);
  populateEnquiry(p);
  setupContactButtons(p);
  setupMap(p);

  setFavoriteButtonState(getFavorites().includes(p.id));

  $("loading").classList.add("hidden");
  $("errorBox").classList.add("hidden");
  $("propertyPage").classList.remove("hidden");
}


/* ---------------- EMI CALCULATOR ---------------- */

function calculateEmi(principal, annualRatePercent, years){
  principal = Number(principal) || 0;
  annualRatePercent = Number(annualRatePercent) || 0;
  years = Number(years) || 0;
  if(principal <= 0 || years <= 0) return 0;
  const monthlyRate = annualRatePercent / 12 / 100;
  const months = years * 12;
  if(monthlyRate <= 0) return principal / months;
  const factor = Math.pow(1 + monthlyRate, months);
  return (principal * monthlyRate * factor) / (factor - 1);
}

function updateEmiResult(){
  const amount = $("emiAmount").value;
  const tenure = $("emiTenure").value;
  const emi = calculateEmi(amount, $("emiRate").value, tenure);
  const totalInterest = emi * (Number(tenure) || 0) * 12 - (Number(amount) || 0);
  $("emiResult").textContent = "₹ " + Math.round(emi).toLocaleString("en-IN");
  $("emiBreakdown").textContent = emi > 0
    ? `Total Interest ≈ ₹ ${Math.round(Math.max(totalInterest, 0)).toLocaleString("en-IN")} over ${tenure} years`
    : "";
}

function setupEmiCalculator(startingPrice){
  const section = $("emiSection");
  if(!startingPrice){
    section.classList.add("hidden");
    return;
  }
  section.classList.remove("hidden");
  $("emiAmount").value = Math.round(startingPrice);
  updateEmiResult();
}

["emiAmount","emiRate","emiTenure"].forEach(id => $(id).addEventListener("input", updateEmiResult));


/* ---------------- GALLERY + LIGHTBOX ---------------- */

function renderGallery(p){
  galleryImages = p.images;
  currentImage = 0;
  $("galleryThumbs").innerHTML = P.renderThumbs(p);

  const none = !galleryImages.length;
  $("mainPhoto").classList.toggle("no-image", none);
  if(none){
    $("mainImage").removeAttribute("src");
    $("mainImage").alt = "No project image available";
  }

  const onlyOne = galleryImages.length < 2;
  ["prevImage","nextImage","imageCounter"].forEach(id => $(id).classList.toggle("hidden", onlyOne));
  updateGallery();
}

function updateGallery(){
  if(!galleryImages.length) return;
  const img = galleryImages[currentImage];
  $("mainImage").src = img.url;
  $("mainImage").alt = img.alt || `${project.name} image ${currentImage + 1}`;
  document.querySelectorAll(".gallery-thumb").forEach((el, i) => el.classList.toggle("active", i === currentImage));
  if(galleryImages.length > 1) $("imageCounter").textContent = `${currentImage + 1} / ${galleryImages.length}`;
}

function nextGallery(step){
  if(galleryImages.length < 2) return;
  currentImage = (currentImage + step + galleryImages.length) % galleryImages.length;
  updateGallery();
}

function openLightbox(index = currentImage){
  if(!galleryImages.length) return;
  currentImage = index;
  updateLightbox();
  $("lightbox").classList.remove("hidden");
  $("lightbox").setAttribute("aria-hidden", "false");
  document.body.style.overflow = "hidden";
}

function closeLightbox(){
  $("lightbox").classList.add("hidden");
  $("lightbox").setAttribute("aria-hidden", "true");
  document.body.style.overflow = "";
}

function updateLightbox(){
  if(!galleryImages.length) return;
  $("lightboxImage").src = galleryImages[currentImage].url;
  $("lightboxCounter").textContent = `${currentImage + 1} / ${galleryImages.length}`;
}

$("galleryThumbs").addEventListener("click", e => {
  const thumb = e.target.closest(".gallery-thumb");
  if(!thumb) return;
  currentImage = Number(thumb.dataset.index) || 0;
  updateGallery();
  openLightbox(currentImage);
});
$("prevImage").addEventListener("click", e => { e.stopPropagation(); nextGallery(-1); });
$("nextImage").addEventListener("click", e => { e.stopPropagation(); nextGallery(1); });
$("mainPhoto").addEventListener("click", e => { if(!e.target.closest("button")) openLightbox(currentImage); });
$("mainPhoto").addEventListener("keydown", e => {
  if(e.key === "Enter" || e.key === " "){ e.preventDefault(); openLightbox(currentImage); }
});
$("lightboxClose").addEventListener("click", closeLightbox);
$("lightboxPrev").addEventListener("click", () => { nextGallery(-1); updateLightbox(); });
$("lightboxNext").addEventListener("click", () => { nextGallery(1); updateLightbox(); });
document.querySelector("[data-close-lightbox]").addEventListener("click", closeLightbox);

let touchStartX = null;
document.addEventListener("touchstart", e => {
  if(e.touches.length === 1) touchStartX = e.touches[0].clientX;
}, { passive:true });
document.addEventListener("touchend", e => {
  if(touchStartX === null || !galleryImages.length) return;
  const dx = e.changedTouches[0].clientX - touchStartX;
  touchStartX = null;
  if(Math.abs(dx) < 45) return;
  if(!$("lightbox").classList.contains("hidden")){ nextGallery(dx < 0 ? 1 : -1); updateLightbox(); }
  else if(e.target.closest("#mainPhoto")) nextGallery(dx < 0 ? 1 : -1);
}, { passive:true });

document.addEventListener("keydown", e => {
  if($("lightbox").classList.contains("hidden")) return;
  if(e.key === "Escape") closeLightbox();
  if(e.key === "ArrowLeft"){ nextGallery(-1); updateLightbox(); }
  if(e.key === "ArrowRight"){ nextGallery(1); updateLightbox(); }
});


/* ---------------- VIDEOS ---------------- */

function renderMedia(p){
  const uploaded = $("uploadedVideos");
  const social = $("socialVideosWrap");
  uploaded.innerHTML = "";
  social.innerHTML = "";

  p.videos.forEach(v => {
    if(/\.(mp4|webm|ogg|mov)(\?|#|$)/i.test(v.url) || /supabase\.co\/storage\//i.test(v.url)){
      const card = document.createElement("div");
      card.className = "video-card";
      card.innerHTML = `<video controls playsinline preload="metadata"><source src="${P.escapeHtml(v.url)}"></video>
        <div class="media-caption">${P.escapeHtml(v.title || (v.type === "virtual_tour" ? "Virtual Tour" : "Project Video"))}</div>`;
      uploaded.appendChild(card);
    }else{
      const type = /youtu/i.test(v.url) ? "youtube" : /facebook|fb\.watch/i.test(v.url) ? "facebook" : /instagram/i.test(v.url) ? "instagram" : "";
      addSocialPlayer(social, v, type);
    }
  });

  $("uploadedVideosWrap").classList.toggle("hidden", !uploaded.children.length);
  $("mediaSection").classList.toggle("hidden", !uploaded.children.length && !social.children.length);
}

function addSocialPlayer(container, video, type){
  const label = type === "youtube" ? "YouTube" : type === "facebook" ? "Facebook" : type === "instagram" ? "Instagram" : "Video";
  const card = document.createElement("div");
  card.className = `social-card ${type}`;
  card.innerHTML = `<div class="social-head"><span>▶</span>${P.escapeHtml(video.title || label + " Video")}</div>`;

  const embed = getSocialEmbed(video.url, type);
  if(embed){
    const iframe = document.createElement("iframe");
    iframe.src = embed;
    iframe.title = `${project.name} ${label} video`;
    iframe.loading = "lazy";
    iframe.allow = "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share";
    iframe.allowFullscreen = true;
    card.appendChild(iframe);
  }
  const footer = document.createElement("div");
  footer.className = "social-footer";
  footer.innerHTML = `<a href="${P.escapeHtml(video.url)}" target="_blank" rel="noopener noreferrer">Open ${P.escapeHtml(label)} ↗</a>`;
  card.appendChild(footer);
  container.appendChild(card);
}

function getSocialEmbed(url, type){
  try{
    const u = new URL(url);
    if(type === "youtube"){
      let id = "";
      if(u.hostname.includes("youtu.be")) id = u.pathname.split("/").filter(Boolean)[0] || "";
      else if(u.searchParams.get("v")) id = u.searchParams.get("v");
      else{
        const parts = u.pathname.split("/").filter(Boolean);
        const i = parts.findIndex(x => ["shorts","embed","live"].includes(x));
        if(i >= 0) id = parts[i + 1] || "";
      }
      return id ? `https://www.youtube.com/embed/${encodeURIComponent(id)}?rel=0` : null;
    }
    if(type === "facebook"){
      return `https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(url)}&show_text=false&width=500`;
    }
    if(type === "instagram"){
      const parts = u.pathname.split("/").filter(Boolean);
      const i = parts.findIndex(x => ["p","reel","reels","tv"].includes(x));
      if(i < 0 || !parts[i + 1]) return null;
      return `https://www.instagram.com/${parts[i] === "reels" ? "reel" : parts[i]}/${encodeURIComponent(parts[i + 1])}/embed/`;
    }
  }catch(_){}
  return null;
}


/* ---------------- MAP ---------------- */

function setupMap(p){
  $("mapBtn").onclick = () => {
    const lat = Number(p.latitude), lng = Number(p.longitude);
    const url = lat && lng
      ? `https://www.google.com/maps?q=${lat},${lng}`
      : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([p.name, p.address, p.location].filter(Boolean).join(", "))}`;
    window.open(url, "_blank", "noopener,noreferrer");
  };
}


/* ---------------- CONTACT (agent first, then site-wide number) ---------------- */

function contactNumbers(p){
  const site = (typeof SITE_CONTACT === "object" && SITE_CONTACT) || {};
  return {
    phone: p.contactPhone || String(site.phone || "").replace(/[^\d+]/g, ""),
    whatsapp: p.contactWhatsapp || String(site.whatsapp || site.phone || "").replace(/\D/g, "")
  };
}

function whatsappMessage(p){
  const bhk = $("enquiryBhk").value;
  return [
    `Hi Keys99, I am interested in ${p.name}${p.location ? ", " + p.location : ""}.`,
    bhk ? `Preferred configuration: ${bhk}` : "",
    window.location.href
  ].filter(Boolean).join("\n");
}

function setupContactButtons(p){
  const { phone, whatsapp } = contactNumbers(p);

  $("stickyCallBtn").disabled = !phone;
  $("stickyCallBtn").onclick = () => { if(phone) window.location.href = "tel:" + phone; };

  $("stickyWhatsappBtn").disabled = !whatsapp;
  $("whatsappBtn").classList.toggle("hidden", !whatsapp);
  const openWhatsapp = () => {
    if(whatsapp) window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(whatsappMessage(p))}`, "_blank", "noopener,noreferrer");
  };
  $("stickyWhatsappBtn").onclick = openWhatsapp;
  $("whatsappBtn").onclick = openWhatsapp;

  $("stickyEnquireBtn").onclick = () => {
    $("enquiryWrap").scrollIntoView({ behavior:"smooth", block:"start" });
    setTimeout(() => $("enquiryName").focus(), 400);
  };
}


/* ---------------- ENQUIRY ---------------- */

function populateEnquiry(p){
  $("enquiryDeveloper").value = p.developer;
  $("enquiryDeveloper").closest("label").classList.toggle("hidden", !p.developer);

  const select = $("enquiryBhk");
  const previous = select.value;
  select.innerHTML = `<option value="">Preferred BHK (optional)</option>` +
    p.bhkLabels.map(l => `<option value="${P.escapeHtml(l)}">${P.escapeHtml(l)}</option>`).join("");
  select.value = p.bhkLabels.includes(previous) ? previous : (p.bhkLabels.length === 1 ? p.bhkLabels[0] : "");
  select.closest("label").classList.toggle("hidden", !p.bhkLabels.length);

  $("enquiryMessage").placeholder = `I'm interested in ${p.name}...`;
}

$("enquiryForm").addEventListener("submit", async event => {
  event.preventDefault();
  if(!project) return;

  const name = $("enquiryName").value.trim();
  const phone = $("enquiryPhone").value.trim();
  const email = $("enquiryEmail").value.trim();
  const bhk = $("enquiryBhk").value.trim();
  const message = $("enquiryMessage").value.trim();

  if(!name || phone.replace(/\D/g, "").length < 10){
    showToast("Please enter your name and a valid WhatsApp number.");
    return;
  }

  const button = $("sendBtn");
  button.disabled = true;
  button.textContent = "Sending...";

  try{
    const { error } = await supabaseClient.from("residential_enquiries").insert({
      project_id: project.id,
      contact_person: name,
      phone,
      whatsapp: phone,
      email: email || null,
      enquiry_type: "enquire_now",
      preferred_contact_method: "whatsapp",
      message: [message || `Interested in ${project.name}.`, bhk ? `Preferred BHK: ${bhk}` : ""].filter(Boolean).join("\n"),
      source: "website"
    });
    if(error) throw error;

    showToast("Enquiry sent. Our expert will contact you soon.");
    $("enquiryForm").reset();
    populateEnquiry(project);
  }catch(error){
    console.error("Enquiry failed:", error);
    showToast("Unable to send the enquiry. Please try again.");
  }finally{
    button.disabled = false;
    button.textContent = "➤  Send Enquiry";
  }
});


/* ---------------- SHARE / FAVORITE / BACK ---------------- */

$("shareBtn").addEventListener("click", async () => {
  if(!project) return;
  try{
    if(navigator.share){
      await navigator.share({ title: project.name, text: `Check out ${project.name} on Keys99.com`, url: window.location.href });
    }else{
      await navigator.clipboard.writeText(window.location.href);
      showToast("Project link copied.");
    }
  }catch(_){}
});

$("favoriteBtn").addEventListener("click", toggleFavorite);

$("backBtn").addEventListener("click", () => {
  if(document.referrer && new URL(document.referrer).origin === window.location.origin) history.back();
  else window.location.href = SITE_ROOT + "index.html";
});

$("enquireTopBtn").addEventListener("click", () => {
  $("enquiryWrap").scrollIntoView({ behavior:"smooth", block:"start" });
});


/* ---------------- MENU / LOGIN ---------------- */

function initMobileMenu(){
  const menuBtn = $("menuBtn");
  const mobileMenu = $("mobileMenu");
  if(!menuBtn || !mobileMenu) return;
  menuBtn.addEventListener("click", () => {
    mobileMenu.classList.toggle("open");
    menuBtn.textContent = mobileMenu.classList.contains("open") ? "×" : "☰";
  });
  mobileMenu.querySelectorAll("a").forEach(link => link.addEventListener("click", () => {
    mobileMenu.classList.remove("open");
    menuBtn.textContent = "☰";
  }));
}

function initLoginButton(){
  const loginBtn = $("loginBtn");
  if(loginBtn) loginBtn.addEventListener("click", () => { window.location.href = SITE_ROOT + "profile.html"; });
}


/* ---------------- ERROR / TOAST ---------------- */

function showError(message){
  $("loading").classList.add("hidden");
  $("propertyPage").classList.add("hidden");
  $("errorBox").classList.remove("hidden");
  const p = $("errorBox").querySelector("p");
  if(p && message) p.textContent = message;
}

let toastTimer;
function showToast(message){
  const toast = $("toast");
  toast.textContent = message;
  toast.classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toast.classList.remove("show"), 2600);
}


/* ---------------- START ---------------- */

initBottomNav();
initMobileMenu();
initLoginButton();
loadProject();
